### PR TITLE
Add EPA adjusted AQI values.

### PR DESCRIPTION
**Pull request by dougkeen**
What I did:

- Added formula for doing EPA adjustment
- Added a field to the model to store the EPA adjusted value separately
_I didn't necessarily want to make that the new "main reading" since the EPA stuff only really applies to wildfire smoke, as opposed to smog or other types of PM2.5 pollution. Maybe make this an option in the client?_

What I didn't do:

- ~~Recompile the model with protobufs (I don't have any of that stuff set up, nor have I done that before)~~
(nevermind, today I learned a new thing... I'd appreciate a sanity check on it, though)

I figured I'd send you this code if you want to merge and/or rework it however you like.

### CODE REVIEW

**Comment by finiteloop** [comment]
If you are good with it, I would prefer to just use this value instead of the existing reading rather than adding both to the protocol buffer. Smaller data output size, and your new function is "more correct" as the default value displayed in the app.

**Comment by dougkeen** [comment]
👍 sounds good to me. Bonus: you won't need new client releases.

**Comment by finiteloop** [comment]
For posterity, I think this is the change we need. Trying to make a test given all the math before I push it out:

```
def _parse_result(result):
    if result.get("DEVICE_LOCATIONTYPE", "outside") != "outside":
        # Skip sensors that are inside
        raise Exception("Device is not outside")
    if int(result["AGE"]) > 300:
        # Ignore device readinds more than 5 minutes old
        raise Exception("Device reading is outdated")
    id = int(result["ID"])
    latitude = float(result["Lat"])
    longitude = float(result["Lon"])
    stats = json.loads(result["Stats"])
    concentration = stats["v1"]
    humidity = result.get("humidity")
    if humidity is not None:
        concentration = _epa_adjustment(concentration, int(humidity))
    reading = aqi_from_pm(concentration)
    return reading


def _epa_adjustment(concentration, relative_humidity):
     if concentration > 250:
         return concentration
     else:
         return 0.534 * concentration - 0.0844 * relative_humidity + 5.604
```

**Comment by pphu** [comment]
@finiteloop It's mention in PR #3 but adding it here for visibility for @dougkeen. Humidity values does not exists on B-channel data. If doing the EPA adjustment, I would recommend filtering out B-channel data or properly link B-channel to A-Channel's humidity reading.

**Comment by dougkeen** [comment]
@finiteloop I'm not sure only doing the EPA adjustment when humidity is available is the right behavior here, since you could end up with an odd mix of adjusted and non-adjusted values on the map. Maybe just assume 50% RH? Take the RH from the next closest sensor? The RH doesn't have a super-huge effect on the adjustment, so I think estimating/fabricating RH would actually end up with less error than using a non-adjusted value.

**Comment by finiteloop** [comment]
Yes agreed. @pphu's suggestion seems right. Will mess around with the data tonight

**Comment by pphu** [comment]
B-Channel is used to check if A-Channel is in agreement. If their values differ greatly, the sensor is marked as unreliable and the whole sensor is excluded from PurpleAir's UI. I believe the pm value is supposed to be averaged between the two channels then add the EPA adjustment. The average shouldn't differ by much since B-Channel is filtering large difference.

**Comment by dougkeen** [comment]
@pphu do you know if the values reported are cf=1 or cf=atm? If it's cf=atm, that could throw off the EPA adjustment (which is based on cf=1).

**Comment by pphu** [comment]
@dougkeen the documentation doesn't appear to state it but your assumption seems right. 

Here's PurpleAir's API for those curious. It might make cleaning up the data earlier and it also appears to group A and B channel together. https://api.purpleair.com/ you have to request api access via email and they'll usually get back within a few days.

**Pull request closed without merging**
